= REST API Guide
김범석, 김하늘;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.


[[resources-index-access]]
=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

// operation::index[snippets='response-body,http-response,links']

[[resources-events]]
== 회원

회원 리소스는 회원 가입, 정보 수정, 로그아웃 및 탈퇴를 할 때 사용한다.

[[resources-events-list]]
=== 회원 가입

`POST` 요청을 사용하여 회원가입을 진행 할 수 있다.

operation::member-signup[snippets='response-fields,curl-request,http-response']

=== 닉네임 중복 검사
`POST` 요청을 사용하여 닉네임 중복을 확인할 수 있다.

operation::nickname-duplicate[snippets='response-fields,curl-request,http-response']

=== 로그인

`POST` 요청을 사용하여 로그인을 진행 할 수 있다.

opertation::login[snippets='response-fields,curl-request,http-response']

=== 회원 정보 수정
`PUT` 요청을 사용하여 회원 정보 수정이 가능하다.

operation::member edit[snippets='response-fields,curl-request,http-response']

=== 로그아웃
`DELETE` 요청을 사용하여 로그아웃이 가능하다.

operation::logout[snippets='response-fields,curl-request,http-response']

=== 이메일 유효성 검사
`POST` 요청을 사용하여 이메일 유효성 검사가 가능하다.

operation::email-validation[snippets='response-fields,curl-request,http-response']

[[resources-events]]
== 게시글

게시글 리소스는 게시글 작성, 조회, 수정 및 삭제 할 때 사용한다.

[[resource-events-list]]
=== 게시글 작성
`POST` 요청을 사용해 게시글 작성을 진행할 수 있다.

operation::post-controller-test/create-post[snippets='request-fields,http-request,response-fields,http-response']

=== 게시글 전체 조회
`GET` 요청을 사용해 게시글 목록을 확인할 수 있다.

operation::post-controller-test/get-all-posts[snippets='request-fields,http-request,response-fields,http-response']

=== 게시글 단건 조회
`GET` 요청을 사용해 게시글을 확인할 수 있다.

operation::post-controller-test/get-post[snippets='request-fields,http-request,response-fields,http-response']

=== 게시글 수정
`PUT` 요청을 사용해 게시글을 수정할 수 있다.

operation::post-controller-test/put-post[snippets='request-fields,http-request,response-fields,http-response']

=== 게시글 삭제
`DELETE` 요청을 사용해 게시글을 삭제 할 수 있다.

operation::post-controller-test/delete-post[snippets='request-fields,http-request,response-fields,http-response']


[[resources-events]]
== 댓글

댓글 리소스는 댓글 작성, 조회, 수정 및 삭제를 할 때 사용한다.

[[resource-events-list]]
=== 댓글 작성
`POST` 요청을 사용해 댓글 작성을 진행 할 수 있다.

operation::create-comment[snippets='request-fields,http-request,response-fields,http-response']

=== 댓글 조회
`GET` 요청을 사용해 댓글 목록을 확인 할 수 있다.

operation::get-comment[snippets='request-fields,http-request,response-fields,http-response']

=== 댓글 수정
`PUT` 요청을 사용해 댓글을 수정 할 수 있다.

operation::update-comment[snippets='request-fields,http-request,response-fields,http-response']

=== 댓글 삭제
`DELETE` 요청을 사용해 댓글을 삭제 할 수 있다.

operation::delete-comment[snippets='request-fields,http-request,response-fields,http-response']


[[resources-events]]
== 모임

모임 리소스는 모임 생성, 조회, 수정 및 삭제를 할 때 사용한다.

[[resource-events-list]]
=== 모임 생성
`POST` 요청을 사용해 모임 생성을 진행 할 수 있다.

operation::meeting-controller-test/create-meeting[snippets='request-fields,http-request,response-fields,http-response']

=== 모임 전체 조회
`GET` 요청을 사용해 모임 목록을 확인 할 수 있다.

operation::meeting-controller-test/get-all-meetings[snippets='request-fields,http-request,response-fields,http-response']

=== 모임 단건 조회
`GET` 요청을 사용해 모임을 확인 할 수 있다.

operation::meeting-controller-test/get-meeting[snippets='request-fields,http-request,response-fields,http-response']

=== 모임 수정
`PUT` 요청을 사용해 모임을 수정 할 수 있다.

operation::meeting-controller-test/put-meeting[snippets='request-fields,http-request,response-fields,http-response']

=== 모임 삭제
`DELETE` 요청을 사용해 모임을 삭제 할 수 있다.

operation::meeting-controller-test/delete-meeting[snippets='request-fields,http-request,response-fields,http-response']



[[resources-events]]
== 마이페이지

마이페이지 리소스는 내 정보 조회, 내가 작성한 게시글 조회, 내가 생성한 모임 조회, 내가 '좋아요한' 게시글 조회를 할 때 사용한다.

[[resource-events-list]]
=== 내 정보 조회
`GET` 요청을 사용해 내 정보를 확인 할 수 있다.

operation::my-page-controller-test/get-my-profile[snippets='request-fields,http-request,response-fields,http-response']

=== 내가 작성한 게시글 조회
`GET` 요청을 사용해 내가 작성한 게시글 목록을 확인 할 수 있다.

operation::my-page-controller-test/get-my-posts[snippets='request-fields,http-request,response-fields,http-response']

=== 내가 생성한 모임 조회
`GET` 요청을 사용해 내가 생성한 모임 목록을 확인 할 수 있다.

operation::my-page-controller-test/get-my-meetings[snippets='request-fields,http-request,response-fields,http-response']

=== 내가 '좋아요'한 게시글 조회
`GET` 요청을 사용해 내가 '좋아요'한 게시글 목록을 확인 할 수 있다.

operation::my-page-controller-test/get-my-heart-posts[snippets='request-fields,http-request,response-fields,http-response']